name: 'Docker Build'

inputs:
  load:
    description: 'Load is a shorthand for --output=type=docker (default false)'
    default: false

outputs:
  image:
    description: 'The image name'
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: 'composite'
  steps:
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: k2wanko/usecase-github-actions-docker-cache
    # Actions のキャッシュを利用する為に、Docker Buildx をセットアップする
    # ref: https://docs.docker.com/build/cache/backends/gha/
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        DOCKER_BUILD_RECORD_UPLOAD: false
        DOCKER_BUILD_SUMMARY: false
      with:
        context: .
        file: ./Dockerfile
        load: ${{ inputs.load }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        # main ブランチの時だけ、キャッシュを保存する
        cache-to: ${{ (github.ref_name == 'main' && 'type=gha,mode=max') || '' }}
        # Dockerfile 側にある ARG を上書きする
        build-args: |
          NPM_CI_ARGS=